@extends('visitor.layouts.app')

@section('main_section')

<div class="container">
    <!-- Title -->
    <div class="hk-pg-header align-items-top">
        <div>
            <h2 class="hk-pg-title font-weight-600 mb-10">PIN Details</h2>
        </div>
    </div>
    <!-- /Title -->
    <!-- Row -->
    @include('messages')
    <div class="row">

        <div class="col-xl-12">
            <div class="hk-row">
            
                <div class="col-lg-12">
                    
                    @if (isset($pin) && !is_null($pin))
                    	
					<div class="table-wrap mb-20">
                        <div class="table-responsive">
                            <table class="table table-bordered mb-0">
                                <thead class="thead-light">
                                    <tr>
                                        <th>PIN</th>
                                        <th>Class</th>
                                        <th>Status</th>
                                        <th>Generated By</th>
                                        <th>Generation Date</th>
                                        <th>Used By</th>
                                        <th>Used Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>{{$pin->pin}}</td>
                                        <td>{{ $pin->class }}</td>
                                        <td>{{ $pin->used_status==0?'Unused' : 'Used' }}</td>
                                        <td>
                                        	@if ($pin->merchant)
                                        		{{ $pin->merchant->name }}
                                        	@endif
                                        </td>
                                        <td>
                                        	@php                                        		
            									$generateDate = substr($pin->date,0,4).'-'.substr($pin->date,4,2).'-'.substr($pin->date, 6,2);
            									echo $generateDate;
                                        	@endphp		
                                        </td>
                                        <td>
                                        	@if ($pin->pinUsage && $pin->pinUsage->visitor)
                                        		{{ $pin->pinUsage->visitor->name }}
                                        	@endif
                                        </td>
                                        <td>                                        	
                                        	@if ($pin->pinUsage)
                                        		
	                                        	@php    
	                                        		$pinU = $pin->pinUsage;                                    		
	            									$usedDate = substr($pinU->date,0,4).'-'.substr($pinU->date,4,2).'-'.substr($pinU->date, 6,2);
	            									echo $usedDate;
	                                        	@endphp	
                                        	@endif
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>

	                    @if (is_null($pin->pinUsage))

		                    <div class="mt-4 text-center">
		                    	<form action="{{ route('visitor.usePin', $pin->id ) }}" method="POST">
		                    		@csrf
		                    		
		                    		<input type="submit" class="btn btn-success" value="Use This PIN">
		                    	</form>
		                    </div>
	                    @endif

	                @elseif (isset($pinReport))
                    	<div class="alert alert-success">
                    		<p>Pin Successfully Used</p>
                    	</div>
                    @else
                    	<div class="alert alert-danger">
                    		<p>Invalid Pin</p>
                    	</div>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <!-- /Row -->
</div>


@endsection
